//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voidSigils.Voids_work.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("voidSigils.Voids_work.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_beesonhit {
            get {
                object obj = ResourceManager.GetObject("ability_beesonhit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bloodguzzler {
            get {
                object obj = ResourceManager.GetObject("ability_bloodguzzler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_BloodGuzzler_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_BloodGuzzler_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bonepicker {
            get {
                object obj = ResourceManager.GetObject("ability_bonepicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bonepicker_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_bonepicker_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_leech {
            get {
                object obj = ResourceManager.GetObject("ability_leech", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_leech_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_leech_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_nutritious {
            get {
                object obj = ResourceManager.GetObject("ability_nutritious", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_poisonous {
            get {
                object obj = ResourceManager.GetObject("ability_poisonous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_poisonous_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_poisonous_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_1 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_1_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_1_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_2_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_2_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_3 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_3_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_3_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_full {
            get {
                object obj = ResourceManager.GetObject("ability_regen_full", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_full_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_full_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_thickshell {
            get {
                object obj = ResourceManager.GetObject("ability_thickshell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_thickshell_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_thickshell_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_transient {
            get {
                object obj = ResourceManager.GetObject("ability_transient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_transient_a2 {
            get {
                object obj = ResourceManager.GetObject("ability_transient_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd0_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd0_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd1_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd1_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd2_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd2_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd3_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd3_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] no_a2 {
            get {
                object obj = ResourceManager.GetObject("no_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Abundance {
            get {
                object obj = ResourceManager.GetObject("void_Abundance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Abundance_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Abundance_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_acid {
            get {
                object obj = ResourceManager.GetObject("void_acid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Acid_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Acid_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Agile {
            get {
                object obj = ResourceManager.GetObject("void_Agile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Agile_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Agile_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_alarm {
            get {
                object obj = ResourceManager.GetObject("void_alarm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush {
            get {
                object obj = ResourceManager.GetObject("void_ambush", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_1 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_2 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_3 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_4 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_5 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_6 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_7 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_8 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_9 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_antler {
            get {
                object obj = ResourceManager.GetObject("void_antler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Blight {
            get {
                object obj = ResourceManager.GetObject("void_Blight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Blight_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Blight_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Blind {
            get {
                object obj = ResourceManager.GetObject("void_Blind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Blind_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Blind_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_bloodgrowth {
            get {
                object obj = ResourceManager.GetObject("void_bloodgrowth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_bodyguard {
            get {
                object obj = ResourceManager.GetObject("void_bodyguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Bodyguard_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Bodyguard_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Bombardier {
            get {
                object obj = ResourceManager.GetObject("void_Bombardier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Bombardier_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Bombardier_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Boneless {
            get {
                object obj = ResourceManager.GetObject("void_Boneless", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_boneless_a2 {
            get {
                object obj = ResourceManager.GetObject("void_boneless_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_BoneShard {
            get {
                object obj = ResourceManager.GetObject("void_BoneShard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_BoneShard_a2 {
            get {
                object obj = ResourceManager.GetObject("void_BoneShard_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_broken {
            get {
                object obj = ResourceManager.GetObject("void_broken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_broken_a2 {
            get {
                object obj = ResourceManager.GetObject("void_broken_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_burning {
            get {
                object obj = ResourceManager.GetObject("void_burning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_burning_a2 {
            get {
                object obj = ResourceManager.GetObject("void_burning_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_caustic {
            get {
                object obj = ResourceManager.GetObject("void_caustic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_caustic_a2 {
            get {
                object obj = ResourceManager.GetObject("void_caustic_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Caustic_Puddle {
            get {
                object obj = ResourceManager.GetObject("void_Caustic_Puddle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Caustic_Puddle_e {
            get {
                object obj = ResourceManager.GetObject("void_Caustic_Puddle_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Caustic_Puddle_p {
            get {
                object obj = ResourceManager.GetObject("void_Caustic_Puddle_p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_coinFinder {
            get {
                object obj = ResourceManager.GetObject("void_coinFinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_coinFinder_a2 {
            get {
                object obj = ResourceManager.GetObject("void_coinFinder_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_consumer {
            get {
                object obj = ResourceManager.GetObject("void_consumer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Coward {
            get {
                object obj = ResourceManager.GetObject("void_Coward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_coward_a2 {
            get {
                object obj = ResourceManager.GetObject("void_coward_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_crate {
            get {
                object obj = ResourceManager.GetObject("void_crate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst {
            get {
                object obj = ResourceManager.GetObject("void_deathburst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_1 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_2 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_3 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_a2 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_desperation {
            get {
                object obj = ResourceManager.GetObject("void_desperation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack {
            get {
                object obj = ResourceManager.GetObject("void_double_attack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_1 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_2 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_3 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_4 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_5 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_6 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_7 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_8 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_9 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_doubleattack_a2 {
            get {
                object obj = ResourceManager.GetObject("void_doubleattack_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawblood {
            get {
                object obj = ResourceManager.GetObject("void_drawblood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawbone {
            get {
                object obj = ResourceManager.GetObject("void_drawbone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawice {
            get {
                object obj = ResourceManager.GetObject("void_drawice", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawice_a2 {
            get {
                object obj = ResourceManager.GetObject("void_drawice_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawjack {
            get {
                object obj = ResourceManager.GetObject("void_drawjack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Dwarf {
            get {
                object obj = ResourceManager.GetObject("void_Dwarf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_dying {
            get {
                object obj = ResourceManager.GetObject("void_dying", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_dying_a2 {
            get {
                object obj = ResourceManager.GetObject("void_dying_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Electric {
            get {
                object obj = ResourceManager.GetObject("void_Electric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Electric_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Electric_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_enforcer {
            get {
                object obj = ResourceManager.GetObject("void_enforcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_enforcer_a2 {
            get {
                object obj = ResourceManager.GetObject("void_enforcer_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_enrage {
            get {
                object obj = ResourceManager.GetObject("void_enrage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_familair {
            get {
                object obj = ResourceManager.GetObject("void_familair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_familair_a2 {
            get {
                object obj = ResourceManager.GetObject("void_familair_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Firestarter {
            get {
                object obj = ResourceManager.GetObject("void_Firestarter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Firestarter_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Firestarter_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fish_hook {
            get {
                object obj = ResourceManager.GetObject("void_fish_hook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fish_hook_a2 {
            get {
                object obj = ResourceManager.GetObject("void_fish_hook_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fisher {
            get {
                object obj = ResourceManager.GetObject("void_fisher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fisher_a2 {
            get {
                object obj = ResourceManager.GetObject("void_fisher_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Giant {
            get {
                object obj = ResourceManager.GetObject("void_Giant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_grazing {
            get {
                object obj = ResourceManager.GetObject("void_grazing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_haste {
            get {
                object obj = ResourceManager.GetObject("void_haste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_haste_a2 {
            get {
                object obj = ResourceManager.GetObject("void_haste_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_0 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_1 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_2 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_3 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Hourglass {
            get {
                object obj = ResourceManager.GetObject("void_Hourglass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_insectKiller {
            get {
                object obj = ResourceManager.GetObject("void_insectKiller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Jack {
            get {
                object obj = ResourceManager.GetObject("void_Jack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Jack_e {
            get {
                object obj = ResourceManager.GetObject("void_Jack_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_lifeStatsUp {
            get {
                object obj = ResourceManager.GetObject("void_lifeStatsUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_lifeStatsUp_a2 {
            get {
                object obj = ResourceManager.GetObject("void_lifeStatsUp_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Maneuver {
            get {
                object obj = ResourceManager.GetObject("void_Maneuver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Maneuver_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Maneuver_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic {
            get {
                object obj = ResourceManager.GetObject("void_Medic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_1 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_2 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_3 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_4 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_5 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_6 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_7 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_8 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_9 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_medic_a2 {
            get {
                object obj = ResourceManager.GetObject("void_medic_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Midas {
            get {
                object obj = ResourceManager.GetObject("void_Midas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_midas_a2 {
            get {
                object obj = ResourceManager.GetObject("void_midas_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_MovementPowerUp {
            get {
                object obj = ResourceManager.GetObject("void_MovementPowerUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_1 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_2 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_3 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_4 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_5 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_6 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_7 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_8 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_9 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_paralysis {
            get {
                object obj = ResourceManager.GetObject("void_paralysis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_paralysis_a2 {
            get {
                object obj = ResourceManager.GetObject("void_paralysis_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_pathetic {
            get {
                object obj = ResourceManager.GetObject("void_pathetic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Pathetic_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Pathetic_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_pierce {
            get {
                object obj = ResourceManager.GetObject("void_pierce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_pierce_a2 {
            get {
                object obj = ResourceManager.GetObject("void_pierce_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_possessor {
            get {
                object obj = ResourceManager.GetObject("void_possessor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_possessor_a2 {
            get {
                object obj = ResourceManager.GetObject("void_possessor_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator {
            get {
                object obj = ResourceManager.GetObject("void_Predator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_1 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_2 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_3 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_4 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_5 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_6 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_7 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_8 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_9 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Prideful {
            get {
                object obj = ResourceManager.GetObject("void_Prideful", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Prideful_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Prideful_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_protector {
            get {
                object obj = ResourceManager.GetObject("void_protector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_protector_a2 {
            get {
                object obj = ResourceManager.GetObject("void_protector_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_randomStrafe {
            get {
                object obj = ResourceManager.GetObject("void_randomStrafe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_randomStrafe_a2 {
            get {
                object obj = ResourceManager.GetObject("void_randomStrafe_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Recoil {
            get {
                object obj = ResourceManager.GetObject("void_Recoil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_recoil_a2 {
            get {
                object obj = ResourceManager.GetObject("void_recoil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_repellant {
            get {
                object obj = ResourceManager.GetObject("void_repellant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_repellant_a2 {
            get {
                object obj = ResourceManager.GetObject("void_repellant_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Resistant {
            get {
                object obj = ResourceManager.GetObject("void_Resistant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Resistant_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Resistant_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Retaliate {
            get {
                object obj = ResourceManager.GetObject("void_Retaliate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Retaliate_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Retaliate_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_scissors {
            get {
                object obj = ResourceManager.GetObject("void_scissors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_scissors_a2 {
            get {
                object obj = ResourceManager.GetObject("void_scissors_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Shocker {
            get {
                object obj = ResourceManager.GetObject("void_Shocker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_shocker_a2 {
            get {
                object obj = ResourceManager.GetObject("void_shocker_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_shove {
            get {
                object obj = ResourceManager.GetObject("void_shove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_shove_a2 {
            get {
                object obj = ResourceManager.GetObject("void_shove_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_sick {
            get {
                object obj = ResourceManager.GetObject("void_sick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_sick_a2 {
            get {
                object obj = ResourceManager.GetObject("void_sick_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_stampede {
            get {
                object obj = ResourceManager.GetObject("void_stampede", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_stampede_a2 {
            get {
                object obj = ResourceManager.GetObject("void_stampede_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_takeDisease {
            get {
                object obj = ResourceManager.GetObject("void_takeDisease", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_takeDisease_a2 {
            get {
                object obj = ResourceManager.GetObject("void_takeDisease_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_thief {
            get {
                object obj = ResourceManager.GetObject("void_thief", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_thief_a2 {
            get {
                object obj = ResourceManager.GetObject("void_thief_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tooth {
            get {
                object obj = ResourceManager.GetObject("void_tooth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tooth_a2 {
            get {
                object obj = ResourceManager.GetObject("void_tooth_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toothGiver {
            get {
                object obj = ResourceManager.GetObject("void_toothGiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toothGiver_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toothGiver_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ToothShard {
            get {
                object obj = ResourceManager.GetObject("void_ToothShard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ToothShard_a2 {
            get {
                object obj = ResourceManager.GetObject("void_ToothShard_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin {
            get {
                object obj = ResourceManager.GetObject("void_toxin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toxin_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_deadly {
            get {
                object obj = ResourceManager.GetObject("void_toxin_deadly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_deadly_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toxin_deadly_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_health {
            get {
                object obj = ResourceManager.GetObject("void_toxin_health", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_health_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toxin_health_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_sickness {
            get {
                object obj = ResourceManager.GetObject("void_toxin_sickness", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_sickness_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toxin_sickness_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_strength {
            get {
                object obj = ResourceManager.GetObject("void_toxin_strength", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_strength_a2 {
            get {
                object obj = ResourceManager.GetObject("void_toxin_strength_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_trample {
            get {
                object obj = ResourceManager.GetObject("void_trample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_trample_a2 {
            get {
                object obj = ResourceManager.GetObject("void_trample_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_bird {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_bird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_canine {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_canine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_hooved {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_hooved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_insect {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_insect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_none {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_none", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_reptile {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_reptile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_bird {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_bird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_canine {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_canine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_hooved {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_hooved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_insect {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_insect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_none {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_none", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_reptile {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_reptile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_vicious {
            get {
                object obj = ResourceManager.GetObject("void_vicious", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_vicious_a2 {
            get {
                object obj = ResourceManager.GetObject("void_vicious_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Volicity {
            get {
                object obj = ResourceManager.GetObject("void_Volicity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Withering {
            get {
                object obj = ResourceManager.GetObject("void_Withering", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Withering_a2 {
            get {
                object obj = ResourceManager.GetObject("void_Withering_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
