//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace voidSigils.Voids_work.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("voidSigils.Voids_work.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_beesonhit {
            get {
                object obj = ResourceManager.GetObject("ability_beesonhit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bloodguzzler {
            get {
                object obj = ResourceManager.GetObject("ability_bloodguzzler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bonedigger {
            get {
                object obj = ResourceManager.GetObject("ability_bonedigger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_bonepicker {
            get {
                object obj = ResourceManager.GetObject("ability_bonepicker", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_leech {
            get {
                object obj = ResourceManager.GetObject("ability_leech", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_nutritious {
            get {
                object obj = ResourceManager.GetObject("ability_nutritious", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_poisonous {
            get {
                object obj = ResourceManager.GetObject("ability_poisonous", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_1 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_2 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_3 {
            get {
                object obj = ResourceManager.GetObject("ability_regen_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_regen_full {
            get {
                object obj = ResourceManager.GetObject("ability_regen_full", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_thickshell {
            get {
                object obj = ResourceManager.GetObject("ability_thickshell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ability_transient {
            get {
                object obj = ResourceManager.GetObject("ability_transient", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] abundance_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("abundance_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] acidtrail_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("acidtrail_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] agile_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("agile_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blight_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("blight_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] blindness_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("blindness_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bloodguzzler_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("bloodguzzler_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bloodless_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("bloodless_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bodyguard_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("bodyguard_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bombardiercool_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("bombardiercool_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] boneless_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("boneless_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] BonelessAct2 {
            get {
                object obj = ResourceManager.GetObject("BonelessAct2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] bonepicker_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("bonepicker_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] boneShard_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("boneShard_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] broken_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("broken_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] burning_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("burning_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] coinFinder_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("coinFinder_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] coward_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("coward_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] deathburst1_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("deathburst1_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] doubleattack_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("doubleattack_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dying_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("dying_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] electric_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("electric_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] familiar_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("familiar_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] firestarter_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("firestarter_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fisher_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("fisher_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] fishhook_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("fishhook_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] goldShard_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("goldShard_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] haste_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("haste_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd0_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd0_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd1_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd1_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd2_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd2_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] herd3_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("herd3_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] leech_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("leech_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] medic_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("medic_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] midas_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("midas_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] opportunist_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("opportunist_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PatheticSacrificeAct2 {
            get {
                object obj = ResourceManager.GetObject("PatheticSacrificeAct2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] piercing_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("piercing_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] poisonous_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("poisonous_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] possessor_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("possessor_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] predator_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("predator_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] prideful_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("prideful_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] protected_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("protected_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rammer_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("rammer_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] randomStrafe_act2 {
            get {
                object obj = ResourceManager.GetObject("randomStrafe_act2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_1_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("regeneration_1_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_2_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("regeneration_2_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_3_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("regeneration_3_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_F_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("regeneration_F_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("regeneration_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] regeneration_sigil_a21 {
            get {
                object obj = ResourceManager.GetObject("regeneration_sigil_a21", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] repellant_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("repellant_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] resistant_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("resistant_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] scissors_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("scissors_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sickly_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("sickly_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] sigilthief_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("sigilthief_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] stampede_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("stampede_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] thickshell_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("thickshell_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tooth_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("tooth_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toothgiver_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("toothgiver_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toxin_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("toxin_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toxin_sigil_a2_A {
            get {
                object obj = ResourceManager.GetObject("toxin_sigil_a2_A", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toxin_sigil_a2_D {
            get {
                object obj = ResourceManager.GetObject("toxin_sigil_a2_D", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toxin_sigil_a2_H {
            get {
                object obj = ResourceManager.GetObject("toxin_sigil_a2_H", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] toxin_sigil_a2_S {
            get {
                object obj = ResourceManager.GetObject("toxin_sigil_a2_S", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] trample_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("trample_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] transient_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("transient_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] vicious_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("vicious_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Abundance {
            get {
                object obj = ResourceManager.GetObject("void_Abundance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_acid {
            get {
                object obj = ResourceManager.GetObject("void_acid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Acid_Puddle {
            get {
                object obj = ResourceManager.GetObject("void_Acid_Puddle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Acid_Puddle_e {
            get {
                object obj = ResourceManager.GetObject("void_Acid_Puddle_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Acid_Puddle_p {
            get {
                object obj = ResourceManager.GetObject("void_Acid_Puddle_p", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_agile {
            get {
                object obj = ResourceManager.GetObject("void_agile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_alarm {
            get {
                object obj = ResourceManager.GetObject("void_alarm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush {
            get {
                object obj = ResourceManager.GetObject("void_ambush", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_1 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_2 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_3 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_4 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_5 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_6 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_7 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_8 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ambush_9 {
            get {
                object obj = ResourceManager.GetObject("void_ambush_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_antler {
            get {
                object obj = ResourceManager.GetObject("void_antler", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_blight {
            get {
                object obj = ResourceManager.GetObject("void_blight", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Blind {
            get {
                object obj = ResourceManager.GetObject("void_Blind", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_bloodgrowth {
            get {
                object obj = ResourceManager.GetObject("void_bloodgrowth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_bodyguard {
            get {
                object obj = ResourceManager.GetObject("void_bodyguard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Bombardier {
            get {
                object obj = ResourceManager.GetObject("void_Bombardier", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Boneless {
            get {
                object obj = ResourceManager.GetObject("void_Boneless", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_BoneShard {
            get {
                object obj = ResourceManager.GetObject("void_BoneShard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_broken {
            get {
                object obj = ResourceManager.GetObject("void_broken", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_burning {
            get {
                object obj = ResourceManager.GetObject("void_burning", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_caustic {
            get {
                object obj = ResourceManager.GetObject("void_caustic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_coinFinder {
            get {
                object obj = ResourceManager.GetObject("void_coinFinder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_consumer {
            get {
                object obj = ResourceManager.GetObject("void_consumer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Coward {
            get {
                object obj = ResourceManager.GetObject("void_Coward", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_crate {
            get {
                object obj = ResourceManager.GetObject("void_crate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst {
            get {
                object obj = ResourceManager.GetObject("void_deathburst", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_1 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_2 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_deathburst_3 {
            get {
                object obj = ResourceManager.GetObject("void_deathburst_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_desperation {
            get {
                object obj = ResourceManager.GetObject("void_desperation", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack {
            get {
                object obj = ResourceManager.GetObject("void_double_attack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_1 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_2 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_3 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_4 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_5 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_6 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_7 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_8 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_double_attack_9 {
            get {
                object obj = ResourceManager.GetObject("void_double_attack_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawblood {
            get {
                object obj = ResourceManager.GetObject("void_drawblood", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawbone {
            get {
                object obj = ResourceManager.GetObject("void_drawbone", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_drawjack {
            get {
                object obj = ResourceManager.GetObject("void_drawjack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Dwarf {
            get {
                object obj = ResourceManager.GetObject("void_Dwarf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_dying {
            get {
                object obj = ResourceManager.GetObject("void_dying", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_eletric {
            get {
                object obj = ResourceManager.GetObject("void_eletric", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_familair {
            get {
                object obj = ResourceManager.GetObject("void_familair", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Firestarter {
            get {
                object obj = ResourceManager.GetObject("void_Firestarter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fish_hook {
            get {
                object obj = ResourceManager.GetObject("void_fish_hook", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_fisher {
            get {
                object obj = ResourceManager.GetObject("void_fisher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Giant {
            get {
                object obj = ResourceManager.GetObject("void_Giant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_grazing {
            get {
                object obj = ResourceManager.GetObject("void_grazing", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_haste {
            get {
                object obj = ResourceManager.GetObject("void_haste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_0 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_1 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_2 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Heard_3 {
            get {
                object obj = ResourceManager.GetObject("void_Heard_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Hourglass {
            get {
                object obj = ResourceManager.GetObject("void_Hourglass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ignit {
            get {
                object obj = ResourceManager.GetObject("void_ignit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_insectKiller {
            get {
                object obj = ResourceManager.GetObject("void_insectKiller", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Jack {
            get {
                object obj = ResourceManager.GetObject("void_Jack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Jack_e {
            get {
                object obj = ResourceManager.GetObject("void_Jack_e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic {
            get {
                object obj = ResourceManager.GetObject("void_Medic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_1 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_2 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_3 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_4 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_5 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_6 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_7 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_8 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Medic_9 {
            get {
                object obj = ResourceManager.GetObject("void_Medic_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Midas {
            get {
                object obj = ResourceManager.GetObject("void_Midas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_MovementPowerUp {
            get {
                object obj = ResourceManager.GetObject("void_MovementPowerUp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_1 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_2 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_3 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_4 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_5 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_6 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_7 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_8 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Opportunist_9 {
            get {
                object obj = ResourceManager.GetObject("void_Opportunist_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_pathetic {
            get {
                object obj = ResourceManager.GetObject("void_pathetic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_pierce {
            get {
                object obj = ResourceManager.GetObject("void_pierce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_possessor {
            get {
                object obj = ResourceManager.GetObject("void_possessor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator {
            get {
                object obj = ResourceManager.GetObject("void_Predator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_1 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_2 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_3 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_4 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_5 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_6 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_7 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_7", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_8 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Predator_9 {
            get {
                object obj = ResourceManager.GetObject("void_Predator_9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Prideful {
            get {
                object obj = ResourceManager.GetObject("void_Prideful", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_protector {
            get {
                object obj = ResourceManager.GetObject("void_protector", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_randomStrafe {
            get {
                object obj = ResourceManager.GetObject("void_randomStrafe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_repellant {
            get {
                object obj = ResourceManager.GetObject("void_repellant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Resistant {
            get {
                object obj = ResourceManager.GetObject("void_Resistant", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_scissors {
            get {
                object obj = ResourceManager.GetObject("void_scissors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_shove {
            get {
                object obj = ResourceManager.GetObject("void_shove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_sick {
            get {
                object obj = ResourceManager.GetObject("void_sick", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_thief {
            get {
                object obj = ResourceManager.GetObject("void_thief", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tooth {
            get {
                object obj = ResourceManager.GetObject("void_tooth", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toothGiver {
            get {
                object obj = ResourceManager.GetObject("void_toothGiver", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_ToothShard {
            get {
                object obj = ResourceManager.GetObject("void_ToothShard", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin {
            get {
                object obj = ResourceManager.GetObject("void_toxin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_deadly {
            get {
                object obj = ResourceManager.GetObject("void_toxin_deadly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_health {
            get {
                object obj = ResourceManager.GetObject("void_toxin_health", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_sickness {
            get {
                object obj = ResourceManager.GetObject("void_toxin_sickness", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_toxin_strength {
            get {
                object obj = ResourceManager.GetObject("void_toxin_strength", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_trample {
            get {
                object obj = ResourceManager.GetObject("void_trample", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_bird {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_bird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_canine {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_canine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_hooved {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_hooved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_insect {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_insect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_none {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_none", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_tribeAlly_reptile {
            get {
                object obj = ResourceManager.GetObject("void_tribeAlly_reptile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_bird {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_bird", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_canine {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_canine", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_hooved {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_hooved", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_insect {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_insect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_none {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_none", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_TribeTutor_reptile {
            get {
                object obj = ResourceManager.GetObject("void_TribeTutor_reptile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_vicious {
            get {
                object obj = ResourceManager.GetObject("void_vicious", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Volicity {
            get {
                object obj = ResourceManager.GetObject("void_Volicity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_Withering {
            get {
                object obj = ResourceManager.GetObject("void_Withering", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] void_zapper {
            get {
                object obj = ResourceManager.GetObject("void_zapper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WitheringAct2 {
            get {
                object obj = ResourceManager.GetObject("WitheringAct2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] zapper_sigil_a2 {
            get {
                object obj = ResourceManager.GetObject("zapper_sigil_a2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
